# .github/workflows/release.yml
name: Release Build

on:
  release:
    types: [published]

jobs:
  build-windows:
    name: Build (Windows, MSVC) and Upload
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust (MSVC)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-x86_64-pc-windows-msvc
          override: true

      - name: Build (release)
        run: cargo build --release

      - name: Upload rs_imgviewer.exe
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/rs_imgviewer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

